
#ifndef DNASEQUENCE_ISEQUENCEANALYSISCOMMAND_H
#define DNASEQUENCE_ISEQUENCEANALYSISCOMMAND_H
#include "../ICommand.h"

class ISequenceAnalysisCommand :public ICommand{

};
#endif //DNASEQUENCE_ISEQUENCEANALYSISCOMMAND_H
